-- Add breakdown columns to parent tables for bidirectional sync
ALTER TABLE rnc_records 
ADD COLUMN IF NOT EXISTS rework_qty DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS loss_qty DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS discard_qty DECIMAL DEFAULT 0;

ALTER TABLE sac_tickets 
ADD COLUMN IF NOT EXISTS rework_qty DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS loss_qty DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS discard_qty DECIMAL DEFAULT 0;
